package cli

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"

	"github.com/mooncitizen/togen/internal/workspace"
)

func exampleProject() map[string]any {
	return map[string]any{
		"version":     1,
		"name":        "shop",
		"provider":    "aws",
		"region":      "eu-west-2",
		"environment": "dev",
		"nodes": []any{
			map[string]any{"id": "n1", "type": "gateway", "name": "api"},
			map[string]any{"id": "n2", "type": "function", "name": "handler"},
			map[string]any{"id": "n3", "type": "database", "name": "main-db"},
		},
		"edges": []any{
			map[string]any{"id": "e1", "from": "n1", "to": "n2", "relation": "routes"},
			map[string]any{"id": "e2", "from": "n2", "to": "n3", "relation": "reads"},
		},
	}
}

func generateCwd(t *testing.T) string {
	t.Helper()
	cwd := t.TempDir()
	if result := Init(cwd, "", "shop", false); result.Code != 0 {
		t.Fatalf("init: %v", result.Lines)
	}
	writeProject(t, cwd, exampleProject())
	return cwd
}

func readDirNames(t *testing.T, dir string) []string {
	t.Helper()
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read dir %s: %v", dir, err)
	}
	names := make([]string, len(entries))
	for i, e := range entries {
		names[i] = e.Name()
	}
	slices.Sort(names)
	return names
}

func readFileText(t *testing.T, path string) string {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(raw)
}

func writeFileText(t *testing.T, path, text string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestGenerateWritesHclFilesAndAManifest(t *testing.T) {
	cwd := generateCwd(t)
	result := Generate(cwd, "", "", false)
	if result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}
	want := []string{
		"wrote 4 files to infra/hcl",
		"  main.tf",
		"  outputs.tf",
		"  providers.tf",
		"  variables.tf",
	}
	if diff := cmp.Diff(want, result.Lines); diff != "" {
		t.Errorf("lines (-want +got):\n%s", diff)
	}

	out := filepath.Join(cwd, "infra", "hcl")
	wantFiles := []string{".togen-manifest.json", "main.tf", "outputs.tf", "providers.tf", "variables.tf"}
	if diff := cmp.Diff(wantFiles, readDirNames(t, out)); diff != "" {
		t.Errorf("files (-want +got):\n%s", diff)
	}

	manifest := readJSONDoc(t, filepath.Join(out, ".togen-manifest.json"))
	wantManifest := map[string]any{
		"version": float64(1),
		"files":   []any{"main.tf", "outputs.tf", "providers.tf", "variables.tf"},
	}
	if diff := cmp.Diff(wantManifest, manifest); diff != "" {
		t.Errorf("manifest (-want +got):\n%s", diff)
	}

	main := readFileText(t, filepath.Join(out, "main.tf"))
	if !strings.HasPrefix(main, "# Generated by Togen from togen/project.json\n") {
		t.Errorf("main.tf does not start with the provenance line: %q", main[:min(60, len(main))])
	}
	if !strings.Contains(main, `resource "aws_db_instance" "main_db"`) {
		t.Error("main.tf has no aws_db_instance resource")
	}
}

func TestGenerateRegeneratesOverItsOwnOutput(t *testing.T) {
	cwd := generateCwd(t)
	if first := Generate(cwd, "", "", false); first.Code != 0 {
		t.Fatalf("first: %v", first.Lines)
	}
	if again := Generate(cwd, "", "", false); again.Code != 0 {
		t.Fatalf("second: %v", again.Lines)
	}
}

func TestGenerateRefusesFilesItDidNotWrite(t *testing.T) {
	cwd := generateCwd(t)
	if first := Generate(cwd, "", "", false); first.Code != 0 {
		t.Fatalf("first: %v", first.Lines)
	}
	stranger := filepath.Join(cwd, "infra", "hcl", "extra.tf")
	writeFileText(t, stranger, "resource \"x\" \"y\" {}\n")

	result := Generate(cwd, "", "", false)
	if result.Code != 1 {
		t.Fatalf("code = %d, want 1", result.Code)
	}
	want := []string{
		"infra/hcl contains files Togen did not write: extra.tf",
		"Move them, or run again with --force to replace the whole directory.",
	}
	if diff := cmp.Diff(want, result.Lines); diff != "" {
		t.Errorf("lines (-want +got):\n%s", diff)
	}
	if !strings.Contains(readFileText(t, stranger), `resource "x"`) {
		t.Error("the stranger was touched")
	}
}

func TestGenerateReplacesTheDirectoryWithForce(t *testing.T) {
	cwd := generateCwd(t)
	if first := Generate(cwd, "", "", false); first.Code != 0 {
		t.Fatalf("first: %v", first.Lines)
	}
	writeFileText(t, filepath.Join(cwd, "infra", "hcl", "extra.tf"), "")
	result := Generate(cwd, "", "", true)
	if result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}
	if slices.Contains(readDirNames(t, filepath.Join(cwd, "infra", "hcl")), "extra.tf") {
		t.Error("extra.tf survived --force")
	}
}

func TestGenerateRefusesUnknownFilesWithNoManifest(t *testing.T) {
	cwd := generateCwd(t)
	writeFileText(t, filepath.Join(cwd, "infra", "hcl", "mine.tf"), "")
	result := Generate(cwd, "", "", false)
	if result.Code != 1 {
		t.Fatalf("code = %d, want 1", result.Code)
	}
	if !strings.Contains(result.Lines[0], "mine.tf") {
		t.Errorf("line = %q, want it to name mine.tf", result.Lines[0])
	}
}

func TestGenerateIgnoresTerraformWorkingFiles(t *testing.T) {
	cwd := generateCwd(t)
	if first := Generate(cwd, "", "", false); first.Code != 0 {
		t.Fatalf("first: %v", first.Lines)
	}
	out := filepath.Join(cwd, "infra", "hcl")
	if err := os.Mkdir(filepath.Join(out, ".terraform"), 0o755); err != nil {
		t.Fatal(err)
	}
	writeFileText(t, filepath.Join(out, ".terraform.lock.hcl"), "")
	writeFileText(t, filepath.Join(out, "terraform.tfstate"), "{}")
	if result := Generate(cwd, "", "", false); result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}
}

func TestGenerateDoesNotRefuseStateAloneInAnUnmanagedDirectory(t *testing.T) {
	cwd := generateCwd(t)
	writeFileText(t, filepath.Join(cwd, "infra", "hcl", "terraform.tfstate"), `{"serial":1}`)
	result := Generate(cwd, "", "", false)
	if result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}
	if got := readFileText(t, filepath.Join(cwd, "infra", "hcl", "terraform.tfstate")); got != `{"serial":1}` {
		t.Errorf("state = %q, want it intact", got)
	}
}

func plantTerraformFiles(t *testing.T, out string) {
	t.Helper()
	writeFileText(t, filepath.Join(out, ".terraform", "providers", "aws"), "provider binary")
	writeFileText(t, filepath.Join(out, ".terraform.lock.hcl"), "lock contents")
	writeFileText(t, filepath.Join(out, "terraform.tfstate"), `{"serial":7}`)
	writeFileText(t, filepath.Join(out, "dev.tfvars"), `region = "eu-west-2"`)
	writeFileText(t, filepath.Join(out, "env", "prod.auto.tfvars"), `size = "large"`)
	writeFileText(t, filepath.Join(out, "env", "eu", "staging.tfvars"), `size = "small"`)
}

func expectTerraformFilesIntact(t *testing.T, out string) {
	t.Helper()
	for path, want := range map[string]string{
		filepath.Join(out, ".terraform", "providers", "aws"): "provider binary",
		filepath.Join(out, ".terraform.lock.hcl"):            "lock contents",
		filepath.Join(out, "terraform.tfstate"):              `{"serial":7}`,
		filepath.Join(out, "dev.tfvars"):                     `region = "eu-west-2"`,
		filepath.Join(out, "env", "prod.auto.tfvars"):        `size = "large"`,
		filepath.Join(out, "env", "eu", "staging.tfvars"):    `size = "small"`,
	} {
		if got := readFileText(t, path); got != want {
			t.Errorf("%s = %q, want %q", path, got, want)
		}
	}
}

func TestGenerateKeepsTerraformFilesOnAPlainRegenerate(t *testing.T) {
	cwd := generateCwd(t)
	if first := Generate(cwd, "", "", false); first.Code != 0 {
		t.Fatalf("first: %v", first.Lines)
	}
	out := filepath.Join(cwd, "infra", "hcl")
	plantTerraformFiles(t, out)
	if result := Generate(cwd, "", "", false); result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}
	expectTerraformFilesIntact(t, out)
}

func TestGenerateKeepsTerraformFilesOnAForcedRegenerate(t *testing.T) {
	cwd := generateCwd(t)
	if first := Generate(cwd, "", "", false); first.Code != 0 {
		t.Fatalf("first: %v", first.Lines)
	}
	out := filepath.Join(cwd, "infra", "hcl")
	plantTerraformFiles(t, out)
	writeFileText(t, filepath.Join(out, "extra.tf"), "")
	if result := Generate(cwd, "", "", true); result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}
	if slices.Contains(readDirNames(t, out), "extra.tf") {
		t.Error("extra.tf survived --force")
	}
	expectTerraformFilesIntact(t, out)
}

func TestGenerateRecoversFromAStaleTogenOld(t *testing.T) {
	cwd := generateCwd(t)
	if first := Generate(cwd, "", "", false); first.Code != 0 {
		t.Fatalf("first: %v", first.Lines)
	}
	stale := filepath.Join(cwd, "infra", "hcl.togen-old")
	writeFileText(t, filepath.Join(stale, "stale.tf"), "")
	if result := Generate(cwd, "", "", false); result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Errorf("stale .togen-old survived: %v", err)
	}
}

func TestGenerateRecoversStateFromATogenOldBesideTheOutput(t *testing.T) {
	cwd := generateCwd(t)
	if first := Generate(cwd, "", "", false); first.Code != 0 {
		t.Fatalf("first: %v", first.Lines)
	}
	out := filepath.Join(cwd, "infra", "hcl")
	old := filepath.Join(cwd, "infra", "hcl.togen-old")
	writeFileText(t, filepath.Join(old, "terraform.tfstate"), `{"serial":11}`)
	writeFileText(t, filepath.Join(old, "main.tf"), "stale")

	if result := Generate(cwd, "", "", false); result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}
	if got := readFileText(t, filepath.Join(out, "terraform.tfstate")); got != `{"serial":11}` {
		t.Errorf("state = %q, want it recovered", got)
	}
	if strings.Contains(readFileText(t, filepath.Join(out, "main.tf")), "stale") {
		t.Error("the stale main.tf replaced the generated one")
	}
	if _, err := os.Stat(old); !os.IsNotExist(err) {
		t.Errorf(".togen-old survived: %v", err)
	}
}

func TestGenerateKeepsTheLiveStateWhenATogenOldAlsoHasOne(t *testing.T) {
	cwd := generateCwd(t)
	if first := Generate(cwd, "", "", false); first.Code != 0 {
		t.Fatalf("first: %v", first.Lines)
	}
	out := filepath.Join(cwd, "infra", "hcl")
	writeFileText(t, filepath.Join(out, "terraform.tfstate"), `{"serial":20}`)
	writeFileText(t, filepath.Join(cwd, "infra", "hcl.togen-old", "terraform.tfstate"), `{"serial":11}`)

	if result := Generate(cwd, "", "", false); result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}
	if got := readFileText(t, filepath.Join(out, "terraform.tfstate")); got != `{"serial":20}` {
		t.Errorf("state = %q, want the live one kept", got)
	}
}

func TestGenerateRecoversFromACrashBetweenTheSwapRenames(t *testing.T) {
	cwd := generateCwd(t)
	if first := Generate(cwd, "", "", false); first.Code != 0 {
		t.Fatalf("first: %v", first.Lines)
	}
	out := filepath.Join(cwd, "infra", "hcl")
	old := filepath.Join(cwd, "infra", "hcl.togen-old")
	if err := os.Rename(out, old); err != nil {
		t.Fatal(err)
	}
	writeFileText(t, filepath.Join(old, "terraform.tfstate"), `{"serial":9}`)

	result := Generate(cwd, "", "", false)
	if result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}
	if got := readFileText(t, filepath.Join(out, "terraform.tfstate")); got != `{"serial":9}` {
		t.Errorf("state = %q, want it recovered", got)
	}
	if _, err := os.Stat(old); !os.IsNotExist(err) {
		t.Errorf(".togen-old survived: %v", err)
	}
}

func TestGenerateHonoursOutAndTarget(t *testing.T) {
	cwd := generateCwd(t)
	result := Generate(cwd, "hcl", "build", false)
	if result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}
	if result.Lines[0] != "wrote 4 files to build/hcl" {
		t.Errorf("line = %q", result.Lines[0])
	}
	if _, err := os.Stat(filepath.Join(cwd, "build", "hcl", "main.tf")); err != nil {
		t.Errorf("build/hcl/main.tf: %v", err)
	}
}

func TestGenerateReportsValidationErrors(t *testing.T) {
	cwd := generateCwd(t)
	project := exampleProject()
	project["edges"] = []any{map[string]any{"id": "e1", "from": "n1", "to": "zz", "relation": "routes"}}
	writeProject(t, cwd, project)

	result := Generate(cwd, "", "", false)
	if result.Code != 1 {
		t.Fatalf("code = %d, want 1", result.Code)
	}
	if !strings.Contains(result.Lines[0], "zz") {
		t.Errorf("line = %q, want it to name zz", result.Lines[0])
	}
	if workspace.Exists(filepath.Join(cwd, "infra")) {
		t.Error("infra/ was written despite the validation failure")
	}
}

func TestGenerateReportsUnsupportedTarget(t *testing.T) {
	cwd := generateCwd(t)
	result := Generate(cwd, "pulumi", "", false)
	if result.Code != 1 {
		t.Fatalf("code = %d, want 1", result.Code)
	}
	if want := "target 'pulumi' is not supported yet"; result.Lines[0] != want {
		t.Errorf("line = %q, want %q", result.Lines[0], want)
	}
}

func TestGenerateReportsUnsupportedProvider(t *testing.T) {
	cwd := generateCwd(t)
	project := exampleProject()
	project["provider"] = "gcp"
	project["region"] = "europe-west2"
	writeProject(t, cwd, project)

	result := Generate(cwd, "", "", false)
	if result.Code != 1 {
		t.Fatalf("code = %d, want 1", result.Code)
	}
	if want := "provider 'gcp' is not supported yet"; result.Lines[0] != want {
		t.Errorf("line = %q, want %q", result.Lines[0], want)
	}
}

func TestGenerateSurfacesResolverErrorsWithTheNode(t *testing.T) {
	cwd := generateCwd(t)
	project := exampleProject()
	project["nodes"] = append(project["nodes"].([]any),
		map[string]any{"id": "n9", "type": "bucket", "name": strings.Repeat("u", 30)})
	writeProject(t, cwd, project)

	result := Generate(cwd, "", "", false)
	if result.Code != 1 {
		t.Fatalf("code = %d, want 1", result.Code)
	}
	if !strings.Contains(result.Lines[0], "the limit is 37") {
		t.Errorf("line = %q, want it to mention the name limit", result.Lines[0])
	}
	if !strings.Contains(result.Lines[0], "n9") {
		t.Errorf("line = %q, want it to name the node", result.Lines[0])
	}
}

// Issue #22: ApplyDefaults ran twice on the way from LoadProject to resolve.Run, and the second
// pass used to re-default a false property back to its jsonschema default. These check the fix
// at the CLI boundary, not just inside the IR package.
func TestGenerateHonoursAFalseAgainstATrueDefault(t *testing.T) {
	cwd := t.TempDir()
	if result := Init(cwd, "", "shop", false); result.Code != 0 {
		t.Fatalf("init: %v", result.Lines)
	}
	writeProject(t, cwd, map[string]any{
		"version":     1,
		"name":        "shop",
		"provider":    "aws",
		"region":      "eu-west-2",
		"environment": "dev",
		"nodes": []any{
			map[string]any{"id": "q1", "type": "queue", "name": "jobs", "properties": map[string]any{"deadLetter": false}},
		},
		"edges": []any{},
	})

	result := Generate(cwd, "", "", false)
	if result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}

	main := readFileText(t, filepath.Join(cwd, "infra", "hcl", "main.tf"))
	if !strings.Contains(main, `resource "aws_sqs_queue" "jobs"`) {
		t.Error("main.tf has no aws_sqs_queue resource for jobs")
	}
	if strings.Contains(main, "jobs_dlq") {
		t.Error("main.tf has a dead-letter queue despite deadLetter: false")
	}
	if strings.Contains(main, "redrive_policy") {
		t.Error("main.tf has a redrive_policy despite deadLetter: false")
	}
}

func TestGenerateHonoursAFalseAgainstATrueDefaultForABucket(t *testing.T) {
	cwd := t.TempDir()
	if result := Init(cwd, "", "shop", false); result.Code != 0 {
		t.Fatalf("init: %v", result.Lines)
	}
	writeProject(t, cwd, map[string]any{
		"version":     1,
		"name":        "shop",
		"provider":    "aws",
		"region":      "eu-west-2",
		"environment": "dev",
		"nodes": []any{
			map[string]any{"id": "b1", "type": "bucket", "name": "uploads", "properties": map[string]any{"versioning": false}},
		},
		"edges": []any{},
	})

	result := Generate(cwd, "", "", false)
	if result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}

	main := readFileText(t, filepath.Join(cwd, "infra", "hcl", "main.tf"))
	if strings.Contains(main, "aws_s3_bucket_versioning") {
		t.Error("main.tf has an aws_s3_bucket_versioning resource despite versioning: false")
	}
}

func TestGenerateReportsAMissingProject(t *testing.T) {
	cwd := t.TempDir()
	if result := Init(cwd, "", "shop", false); result.Code != 0 {
		t.Fatalf("init: %v", result.Lines)
	}
	if err := os.Remove(workspace.ProjectPath(cwd)); err != nil {
		t.Fatal(err)
	}
	result := Generate(cwd, "", "", false)
	if result.Code != 1 {
		t.Fatalf("code = %d, want 1", result.Code)
	}
	if want := "togen/project.json not found. Run 'togen init' first."; result.Lines[0] != want {
		t.Errorf("line = %q, want %q", result.Lines[0], want)
	}
}

func TestGenerateNotesTheLegacyConfig(t *testing.T) {
	cwd := generateCwd(t)
	if result := Generate(cwd, "", "", false); result.Note != "" {
		t.Errorf("note = %q, want none", result.Note)
	}

	legacyConfig(t, cwd)
	result := Generate(cwd, "", "", true)
	if result.Code != 0 {
		t.Fatalf("code = %d, lines = %v", result.Code, result.Lines)
	}
	if result.Note != workspace.LegacyNote {
		t.Errorf("note = %q, want %q", result.Note, workspace.LegacyNote)
	}
}
