package hcl

import (
	"bytes"
	"fmt"

	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/zclconf/go-cty/cty"

	"github.com/mooncitizen/togen/internal/ir"
)

const header = "# Generated by Togen from togen/project.json"

func Emit(g *ir.Graph) (map[string][]byte, error) {
	files := map[string][]byte{}

	providers, err := emitProviders(g)
	if err != nil {
		return nil, err
	}
	files["providers.tf"] = providers

	main, err := emitMain(g)
	if err != nil {
		return nil, err
	}
	files["main.tf"] = main

	if len(g.Variables) > 0 {
		variables, err := emitVariables(g.Variables)
		if err != nil {
			return nil, err
		}
		files["variables.tf"] = variables
	}
	if len(g.Outputs) > 0 {
		outputs, err := emitOutputs(g.Outputs)
		if err != nil {
			return nil, err
		}
		files["outputs.tf"] = outputs
	}
	return files, nil
}

func newFile() *hclwrite.File {
	f := hclwrite.NewEmptyFile()
	f.Body().AppendUnstructuredTokens(comment(header))
	f.Body().AppendNewline()
	return f
}

func comment(text string) hclwrite.Tokens {
	return hclwrite.Tokens{{Type: hclsyntax.TokenComment, Bytes: []byte(text + "\n")}}
}

func emitProviders(g *ir.Graph) ([]byte, error) {
	f := newFile()
	body := f.Body()

	tf := body.AppendNewBlock("terraform", nil)
	tf.Body().SetAttributeValue("required_version", cty.StringVal(g.TerraformVersion))
	tf.Body().AppendNewline()
	required := tf.Body().AppendNewBlock("required_providers", nil)
	required.Body().SetAttributeRaw(g.Provider.Name, hclwrite.TokensForObject([]hclwrite.ObjectAttrTokens{
		{Name: hclwrite.TokensForIdentifier("source"), Value: quoted(g.Provider.Source)},
		{Name: hclwrite.TokensForIdentifier("version"), Value: quoted(g.Provider.Version)},
	}))

	body.AppendNewline()
	provider := body.AppendNewBlock("provider", []string{g.Provider.Name})
	if _, err := setArgs(provider.Body(), false, g.Provider.Config); err != nil {
		return nil, fmt.Errorf("provider %s: %w", g.Provider.Name, err)
	}
	return hclwrite.Format(f.Bytes()), nil
}

type group struct {
	label  string
	blocks []*hclwrite.Block
}

func emitMain(g *ir.Graph) ([]byte, error) {
	var groups []group

	for _, d := range g.Data {
		b := hclwrite.NewBlock("data", []string{d.Type, d.Name})
		if _, err := setArgs(b.Body(), false, d.Args); err != nil {
			return nil, fmt.Errorf("data %s.%s: %w", d.Type, d.Name, err)
		}
		groups = place(groups, d.SourceLabel, b)
	}

	for _, r := range g.Resources {
		b := hclwrite.NewBlock("resource", []string{r.Type, r.Name})
		wrote, err := setArgs(b.Body(), false, r.Args)
		if err != nil {
			return nil, fmt.Errorf("resource %s.%s: %w", r.Type, r.Name, err)
		}
		if len(r.DependsOn) > 0 {
			refs := make([]hclwrite.Tokens, 0, len(r.DependsOn))
			for _, d := range r.DependsOn {
				refs = append(refs, hclwrite.TokensForTraversal(traversal(ir.Ref{Kind: ir.RefResource, Target: d})))
			}
			if wrote {
				b.Body().AppendNewline()
			}
			b.Body().SetAttributeRaw("depends_on", hclwrite.TokensForTuple(refs))
		}
		groups = place(groups, r.SourceLabel, b)
	}

	f := newFile()
	body := f.Body()
	for i, grp := range groups {
		if i > 0 {
			body.AppendNewline()
		}
		if grp.label != "" {
			body.AppendUnstructuredTokens(comment("# " + grp.label))
			body.AppendNewline()
		}
		for j, b := range grp.blocks {
			if j > 0 {
				body.AppendNewline()
			}
			body.AppendBlock(b)
		}
	}
	return hclwrite.Format(f.Bytes()), nil
}

func place(groups []group, label string, b *hclwrite.Block) []group {
	for i := range groups {
		if groups[i].label == label {
			groups[i].blocks = append(groups[i].blocks, b)
			return groups
		}
	}
	return append(groups, group{label: label, blocks: []*hclwrite.Block{b}})
}

func emitVariables(vars []ir.Variable) ([]byte, error) {
	f := newFile()
	for i, v := range vars {
		if i > 0 {
			f.Body().AppendNewline()
		}
		b := f.Body().AppendNewBlock("variable", []string{v.Name})
		body := b.Body()

		var head ir.Attrs
		if v.Description != "" {
			head.Set("description", ir.String(v.Description))
		}
		if _, err := setArgs(body, false, head); err != nil {
			return nil, fmt.Errorf("variable %s: %w", v.Name, err)
		}

		// type is a bare identifier, not a quoted string, so it has no ir.Value
		// representation and is written raw. It still feeds the wrote flag below,
		// so a multi-line default after it still gets its blank line.
		body.SetAttributeRaw("type", hclwrite.TokensForIdentifier(v.Type))

		if _, isBlock := v.Default.(ir.Block); isBlock {
			return nil, fmt.Errorf("variable %s: a block cannot be used as a value", v.Name)
		}
		var tail ir.Attrs
		if v.Default != nil {
			tail.Set("default", v.Default)
		}
		if v.Sensitive {
			tail.Set("sensitive", ir.Bool(true))
		}
		if _, err := setArgs(body, true, tail); err != nil {
			return nil, fmt.Errorf("variable %s: %w", v.Name, err)
		}
	}
	return hclwrite.Format(f.Bytes()), nil
}

func emitOutputs(outs []ir.Output) ([]byte, error) {
	f := newFile()
	for i, o := range outs {
		if i > 0 {
			f.Body().AppendNewline()
		}
		b := f.Body().AppendNewBlock("output", []string{o.Name})

		if _, isBlock := o.Value.(ir.Block); isBlock {
			return nil, fmt.Errorf("output %s: a block cannot be used as a value", o.Name)
		}
		var attrs ir.Attrs
		if o.Description != "" {
			attrs.Set("description", ir.String(o.Description))
		}
		attrs.Set("value", o.Value)
		if o.Sensitive {
			attrs.Set("sensitive", ir.Bool(true))
		}
		if _, err := setArgs(b.Body(), false, attrs); err != nil {
			return nil, fmt.Errorf("output %s: %w", o.Name, err)
		}
	}
	return hclwrite.Format(f.Bytes()), nil
}

func setArgs(body *hclwrite.Body, wrote bool, args ir.Attrs) (bool, error) {
	for _, a := range args {
		if blk, ok := a.Value.(ir.Block); ok {
			for _, entry := range blk {
				if wrote {
					body.AppendNewline()
				}
				if _, err := setArgs(body.AppendNewBlock(a.Key, nil).Body(), false, entry); err != nil {
					return false, fmt.Errorf("%s: %w", a.Key, err)
				}
				wrote = true
			}
			continue
		}
		t, err := tokens(a.Value)
		if err != nil {
			return false, fmt.Errorf("%s: %w", a.Key, err)
		}
		if wrote && multiline(t) {
			body.AppendNewline()
		}
		body.SetAttributeRaw(a.Key, t)
		wrote = true
	}
	return wrote, nil
}

func multiline(t hclwrite.Tokens) bool {
	for _, tok := range t {
		if bytes.IndexByte(tok.Bytes, '\n') != -1 {
			return true
		}
	}
	return false
}
