name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-plugins-${{ hashFiles('internal/resolve/aws/provider.go') }}
      - run: nix develop -c make check
      - run: nix develop -c golangci-lint run ./...
      - run: nix develop -c make build
      - run: nix develop -c make acceptance
